@startuml Cas_utilisation
left to right direction

actor "Formateur" as fr
actor "Responsable des Stagiaires" as rs

rectangle EntretienInscription {
  usecase "Voir les analyses" as UC1
  usecase "CRUD Modèles des entretiens" as UC2
  usecase "CRUD Type des questions" as UC3
  usecase "CRUD Questiones" as UC4
  usecase "CRUD Entretiens" as UC5
  usecase "Evaluer un inscrit" as UC6
}

fr -- UC1
fr -- UC2
fr -- UC3
fr -- UC5

rs -- UC1
rs -- UC2
rs -- UC3
rs -- UC5

UC3 <.. UC4 : <<extends>>
UC5 <.. UC6 : <<extends>>
@enduml
