@startuml Sprint_2
left to right direction
actor "Formateur" as fr
rectangle System {
  usecase "CRUD Branche" as UC1
  usecase "CRUD Question" as UC2
  usecase "Entretien" as UC3
}
fr -- UC1
UC1 <.. UC2 : <<extends>>
fr -- UC3
@enduml
