@startuml Sprint_2
left to right direction
actor "Formateur" as fr
actor "Responsable des Stagiaires" as rs
rectangle EntretienInscription {
  usecase "CRUD EntretienTemplates" as UC1
  usecase "CRUD TypeQuestions" as UC2
  usecase "CRUD Questiones" as UC3
}

fr -- UC1
fr -- UC2

rs -- UC1
rs -- UC2

UC2 <.. UC3 : <<extends>>
@enduml
