<?php

namespace  Modules\Interview\database\seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParticipationSeeder extends Seeder
{
    public function run()
    {
        DB::table('participations')->insert([
            [
                'candidate_id'   => 1,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'completed',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 2,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 3,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'completed',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 4,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 5,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'completed',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 6,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 7,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'completed',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 8,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 9,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'completed',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 10,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 11,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'completed',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 12,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 13,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'completed',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 14,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 15,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'absent',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 16,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 17,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'pending',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 18,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 19,
                'interview_id'   => 1,
                'trainer_id'     => 1,
                'status'         => 'pending',
                'report'         => 'Excellent communication skills.',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'candidate_id'   => 20,
                'interview_id'   => 1,
                'trainer_id'     => 2,
                'status'         => 'pending',
                'report'         => null,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
