%%{init: {'theme': 'base', 'themeVariables': {'primaryColor': '#B0E2FF', 'edgeLabelBackground': '#E6F7FF', 'tertiaryColor': '#D9F2FF'}}}%%

classDiagram
  class Branch {
    + int id
    + string name
    + date createdAt
    + date udatedAt
  }

  class Question {
    + int id
    + string content
    + date createdAt
    + date udatedAt
  }

  Branch "*" -- "1" Question
