classDiagram

namespace PkgEntretienInscription {
  class EntretienModèle
  class Entretien
  class TypeQuestion
  class Question
  class Evaluation
}

class EntretienModèle {
  id : ID
  title: string
  created_at : date
  updated_at : date
}

class Entretien {
  id : ID
  status : string
  date: date
  created_at : date
  updated_at : date
}

class TypeQuestion {
  id : ID
  title : string
  created_at : date
  updated_at : date
}

class Question {
  id : ID
  title : string
  created_at : date
  updated_at : date
}

class Evaluation{
  id : ID
  note : float
  remarques : string
  created_at : date
  updated_at : date
}

namespace PkgTestInscription {
  class Inscrit
}

class Inscrit {
  id : ID
  nom : string
  created_at : date
  updated_at : date
}

namespace PkgUtilisateurs {
  class Evaluateur
}

class Evaluateur {
  id : ID
  nom : string
  created_at : date
  updated_at : date
}

Inscrit "1" -- "*" Entretien
Entretien "1" -- "*" Evaluation
TypeQuestion "1" -- "*" Question
Evaluateur "1" -- "*" Evaluation
EntretienModèle "1" -- "*" Entretien
TypeQuestion "*" -- "*" EntretienModèle
Question "1" -- "*" Evaluation
