classDiagram

namespace PkgEntretienInscription {
  class Entretien
  class Participation
  class Branche
  class Question
  class Reponse
  class Evaluation
}

class Entretien {
  id : ID
  title: string
  created_at : date
  updated_at : date
}

class Participation {
  id : ID
  status : string
  created_at : date
  updated_at : date
}

class Branche {
  id : ID
  title : string
}

class Question {
  id : ID
  text : string
}

class Reponse {
  id : ID
  created_at : date
  updated_at : date
}

class Evaluation{
  id : ID
  note : float
  remarques : string
}

namespace PkgTestInscription {
  class Inscrit
}

class Inscrit {
  id : ID
  nom : string
}

namespace PkgUtilisateurs {
  class Formateur
}

class Formateur {
  id : ID
  nom : string
  email : string
}


Inscrit "1" --> "*" Participation
Participation "1" --> "*" Reponse
Formateur "*" -- "*" Participation
Branche "1" --> "*" Question
Reponse "1" --> "1" Evaluation
Formateur "1" --> "*" Evaluation
Entretien "1" --> "*" Participation
Branche "*" -- "*" Entretien
Question "1" --> "*" Reponse
